version: '3'
services:
  cnil-pia-back:
    container_name: LINCnil-pia-back
    build: docker/cnil-pia-back
    restart: always
    environment:
      DATABASE_HOST: 'database'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'somepassword'
      SECRET_KEY_BASE: 'somesecret'
    links:
      - database
    depends_on:
      - database
    ports:
      - 3000:3000

  cnil-pia-front:
    container_name: LINCnil-pia-front
    build: 
      context: docker/cnil-pia-front
      dockerfile: Dockerfile
      args:
        PIA_BACKEND_URL: '<pia_backend_url_value>'
        ATHORA_RETRIEVE_PROFILE: '<athora_retrieve_profile_value>'
        ATHORA_GET_AVAILABLE_USERS: '<athora_get_available_users_value>'
    restart: always
    ports:
      - 0.0.0.0:8080:80

  database:
    container_name: LINCnil-pia-db
    image: postgres:11.0
    restart: always
    environment:
      POSTGRES_PASSWORD: 'somepassword'